/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Run */
        get: operations["read_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Report */
        get: operations["read_report_runs__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Traces */
        get: operations["read_traces_runs__run_id__traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/diff/{other_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff Runs */
        get: operations["diff_runs_runs__run_id__diff__other_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentTrace
         * @description The ordered record of a finished or stopped run.
         */
        AgentTrace: {
            /** Events */
            events: components["schemas"]["TraceEvent"][];
            /** Final Text */
            final_text: string;
        };
        /**
         * DiffBody
         * @description Scenario ids that changed outcome. `left` is the first run in the URL.
         */
        DiffBody: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioDiff"][];
        };
        /**
         * FailingRule
         * @description One rule that failed for a scenario.
         */
        FailingRule: {
            /** Id */
            id: string;
            /** Severity */
            severity: string;
            /** Reason */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ReportBody
         * @description The bytes that get signed. Fields are the Phase 6 schema.
         */
        ReportBody: {
            /** Agent Id */
            agent_id: string;
            /** Scenario Pack Hash */
            scenario_pack_hash: string;
            /** Policy Version */
            policy_version: number;
            /** Created At */
            created_at: string;
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioOutcome"][];
            /** Trace Refs */
            trace_refs: components["schemas"]["TraceRef"][];
        };
        /**
         * RunAccepted
         * @description The id a client polls. The suite has not run yet.
         */
        RunAccepted: {
            /** Id */
            id: string;
            /**
             * Status
             * @constant
             */
            status: "queued";
        };
        /**
         * RunCreate
         * @description The suite directory, the agent entry, and the policy file to score with.
         */
        RunCreate: {
            /** Suite */
            suite: string;
            /** Agent */
            agent: string;
            /** Policy */
            policy: string;
        };
        /**
         * RunList
         * @description Runs newest first.
         */
        RunList: {
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /**
         * RunStatusBody
         * @description What `GET /runs/{id}` returns.
         */
        RunStatusBody: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Agent */
            agent: string;
            /** Suite Hash */
            suite_hash: string;
            /** Policy Hash */
            policy_hash: string;
            /** Created At */
            created_at: string;
            /** Error */
            error?: string | null;
        };
        /**
         * RunSummary
         * @description One row on the runs list.
         */
        RunSummary: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Agent */
            agent: string;
            /** Created At */
            created_at: string;
            /** Passed Count */
            passed_count: number;
            /** Scenario Count */
            scenario_count: number;
        };
        /**
         * RunTraces
         * @description Traces for a finished run, in scenario id order.
         */
        RunTraces: {
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioTrace"][];
        };
        /**
         * ScenarioDiff
         * @description One scenario whose pass/fail is not the same on the two runs.
         */
        ScenarioDiff: {
            /** Id */
            id: string;
            /** Severity */
            severity: string;
            /** Left Passed */
            left_passed: boolean | null;
            /** Right Passed */
            right_passed: boolean | null;
        };
        /**
         * ScenarioOutcome
         * @description Pass or fail for one scenario, plus the rule ids and excerpt a reviewer needs.
         */
        ScenarioOutcome: {
            /** Id */
            id: string;
            /** Suite */
            suite: string;
            /** Passed */
            passed: boolean;
            /** Deciding Event */
            deciding_event?: number | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Failing Rules */
            failing_rules?: components["schemas"]["FailingRule"][];
            /**
             * Excerpt
             * @default
             */
            excerpt: string;
        };
        /**
         * ScenarioTrace
         * @description The stored trace for one scenario.
         */
        ScenarioTrace: {
            /** Scenario Id */
            scenario_id: string;
            trace: components["schemas"]["AgentTrace"];
        };
        /**
         * SignedReport
         * @description A report body plus the signature over its canonical bytes.
         */
        SignedReport: {
            report: components["schemas"]["ReportBody"];
            /** Signature */
            signature: string;
            /**
             * Algorithm
             * @enum {string}
             */
            algorithm: "local" | "ML-DSA-44" | "qknot";
        };
        /**
         * TraceEvent
         * @description One recorded moment in a run.
         */
        TraceEvent: {
            /** Sequence */
            sequence: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "llm_call" | "tool_call" | "tool_result" | "final";
            /** Name */
            name?: string | null;
            /** Text */
            text?: string | null;
            /** Arguments */
            arguments?: {
                [key: string]: unknown;
            } | null;
            /** Output */
            output?: string | null;
            /** Started Ns */
            started_ns?: number | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Token Count */
            token_count?: number | null;
            /** Args Sha256 */
            args_sha256?: string | null;
        };
        /**
         * TraceRef
         * @description Sha256 of one scenario's canonical trace JSON.
         */
        TraceRef: {
            /** Scenario Id */
            scenario_id: string;
            /** Sha256 */
            sha256: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatusBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_report_runs__run_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignedReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_traces_runs__run_id__traces_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTraces"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diff_runs_runs__run_id__diff__other_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                other_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
